{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from gpad_data_generation import *\n",
    "from data_loader import *\n",
    "import sounddevice as sd\n",
    "import numpy as np\n",
    "\n",
    "# To parse the xml\n",
    "file = \"extendedballroom_v1.1.xml\"\n",
    "import xml.etree.ElementTree as ET\n",
    "tree = ET.parse(file)\n",
    "root = tree.getroot()\n",
    "# To mesure the running time\n",
    "import time\n",
    "# To store the data\n",
    "import h5py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "We've already made 0 calculations.\n",
      "We've already made 100 calculations.\n",
      "We've already made 200 calculations.\n",
      "We've already made 300 calculations.\n",
      "We've already made 400 calculations.\n",
      "We've already made 500 calculations.\n",
      "We've already made 600 calculations.\n",
      "We've already made 700 calculations.\n",
      "We've already made 800 calculations.\n",
      "We've already made 900 calculations.\n",
      "We've already made 1000 calculations.\n",
      "We've already made 1100 calculations.\n",
      "We've already made 1200 calculations.\n",
      "We've already made 1300 calculations.\n",
      "We've already made 1400 calculations.\n",
      "We've already made 1500 calculations.\n",
      "We've already made 1600 calculations.\n",
      "We've already made 1700 calculations.\n",
      "We've already made 1800 calculations.\n",
      "We've already made 1900 calculations.\n",
      "We've already made 2000 calculations.\n",
      "We've already made 2100 calculations.\n",
      "We've already made 2200 calculations.\n",
      "We've already made 2300 calculations.\n",
      "We've already made 2400 calculations.\n",
      "We've already made 2500 calculations.\n",
      "We've already made 2600 calculations.\n",
      "We've already made 2700 calculations.\n",
      "We've already made 2800 calculations.\n",
      "We've already made 2900 calculations.\n",
      "We've already made 3000 calculations.\n",
      "We've already made 3100 calculations.\n",
      "We've already made 3200 calculations.\n",
      "We've already made 3300 calculations.\n",
      "We've already made 3400 calculations.\n",
      "We've already made 3500 calculations.\n",
      "We've already made 3600 calculations.\n",
      "We've already made 3700 calculations.\n",
      "We've already made 3800 calculations.\n",
      "We've already made 3900 calculations.\n",
      "We've already made 4000 calculations.\n",
      "We've already made 4100 calculations.\n",
      "O tempo de execução foi de 3373.8065044879913 segundos\n"
     ]
    }
   ],
   "source": [
    "# xml parsing\n",
    "start = time.time()\n",
    "i = 0\n",
    "i_break = -1\n",
    "for elem in root:\n",
    "    # Here we collect the name of the directory\n",
    "    directory = str(elem.tag) + \"/\"\n",
    "    # print(directory)\n",
    "    for subelem in elem:\n",
    "        # Here we collect the name of file\n",
    "        music = subelem.attrib['id'] + \".mp3\"\n",
    "        music_name = subelem.attrib['title']        \n",
    "        bbpm = int(subelem.attrib['bpm'])\n",
    "        filename = directory + music\n",
    "        nivel_wavelet = 2\n",
    "        try:\n",
    "            # Here we get the ODFs, PeDFs and coeffs\n",
    "            ODF_SET, PeDF_FULL_SET, PeDF_PARTIAL_SET, coeffs = music_processor(filename, start_sample=2**19, final_sample=2**20, sample_rate=44100, nivel_wavelet = 2)\n",
    "\n",
    "            # Opening the hdf5 file\n",
    "            hf = h5py.File('h5/n2data_extended_ballroom_' + str(i) + '.hdf5','a')\n",
    "\n",
    "            # Storing Arrays\n",
    "            ODF = hf.create_group('ODF')\n",
    "            PeDFfull = hf.create_group('PeDFfull')\n",
    "            PeDFpartial = hf.create_group('PeDFpartial')\n",
    "            #coeffswav = hf.create_group('coeffswav')\n",
    "\n",
    "            for j in range(0,nivel_wavelet+1):\n",
    "                ODF.create_dataset(\"ODF\" + str(j), data=ODF_SET[j])\n",
    "                PeDFfull.create_dataset(\"PeDFfull\" + str(j), data=PeDF_FULL_SET[j])\n",
    "                PeDFpartial.create_dataset(\"PeDFpartial\" + str(j), data=PeDF_PARTIAL_SET[j])\n",
    "                #coeffswav.create_dataset(\"coeffswav\" + str(j), data=coeffs[j])\n",
    "\n",
    "            bbbpm = np.array((1,1))\n",
    "            bbbpm = bbpm\n",
    "            bpm = hf.create_group('bpm')\n",
    "            bpm.create_dataset(\"bpm\", data=bbbpm)\n",
    "\n",
    "            # Storing Strings\n",
    "            # TODO - music / genre / title\n",
    "\n",
    "            # Closing the hdf5 file\n",
    "            hf.close()\n",
    "        except:\n",
    "            continue\n",
    "        \n",
    "        # Shows\n",
    "        if i%100 == 0:\n",
    "            print(f\"We've already made {i} calculations.\")\n",
    "\n",
    "        i = i + 1\n",
    "        if i == i_break:\n",
    "            break\n",
    "    if i == i_break:\n",
    "        break\n",
    "        \n",
    "end = time.time()\n",
    "print(f\"O tempo de execução foi de {end - start} segundos\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
